### ISSUE TITLE
How if our class model more than 2?

### ISSUE THREAD

**Issue by Waruhu** [pranavj1001/Image-Classification#1]
This program assumes that you have only two classes to classify from images. Slight changes need to be done if you have multiple classes of images. In future, I'll add a separate python script for this.?

can you give me the changes?

**Comment by pranavj1001** [comment]
My exams got over today. Give me some time I'll add the script.

**Comment by pranavj1001** [comment]
I've added the script. Please have a look at it. Here's the [link](https://github.com/pranavj1001/Image-Classification/blob/master/More_than_two_Classes/CNN_Classification_Multi_Class.py).
I'm closing this issue.

**Comment by Waruhu** [comment]
Thank you very much
